version: '3.7'
services:
  db:
    image: postgres:14.1-alpine
    container_name: pomegranate-psql
    restart: "no"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: "postgres"
      #POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
